run:
  concurrency: 4

  skip-dirs:
    - vendor
    - .git
    - .github
    - .idea

  skip-files:
    - dead-tests/go_test.go

linters:
  enable-all: true
  disable:
    - forbidigo
    - gochecknoglobals
    - wrapcheck
    - ifshort
    - exhaustivestruct
    - golint
    - scopelint
    - interfacer
    - maligned
    - nosnakecase

linters-settings:
  cyclop:
    max-complexity: 18
  varnamelen:
    min-name-length: 1
  nestif:
    min-complexity: 30
  gocognit:
    min-complexity: 60

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - exhaustruct
        - varnamelen
        - funlen
