name: test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: on
  GO_VERSION: "1.19.x"

jobs:
  test:
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
            go: [1.17.x, 1.18.x, 1.19.x]
        fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go }}-cache

      - name: Test
        id: test
        run: |
          make test

      - name: Upload coverage to Codecov
        if: matrix.go == env.GO_LATEST_VERSION
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          flags: unittests-${{ matrix.os }}
